spring.application.name=goat
spring.data.mongodb.uri=mongodb+srv://hoang:%40Hoang17102003@cluster0.t6ogryb.mongodb.net/goat?appName=Cluster0
server.port=8080
app.jwt.secret=goat-farm-jwt-secret-key-minimum-32-characters-long-2024
app.jwt.expiration=604800000
app.auth.username=admin
app.auth.password=admin123
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/plain
server.compression.min-response-size=1024
